import { useRef, Suspense, useEffect, useState } from "react";
import "../App.css";

import { Canvas, useFrame, useThree,  } from "@react-three/fiber";
import {
  useGLTF,
  Stage,
  OrthographicCamera,
  OrbitControls, PerspectiveCamera
} from "@react-three/drei";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { Perf } from "r3f-perf";
import * as THREE from 'three'
import Cannon from "./Cannon";
import { RigidBody } from "@react-three/rapier";
function Target({position, targetsWidth, targetsHeightDiff, targetSpin}) {
  const scale = [1.5,1.5,1.5]
  const { nodes: targetNodes, materials: targetMaterials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target/model.gltf"
  );
    // useFrame((state,delta) => {
        // state.camera.lookAt([0,0,0])
    const { camera, scene } = useThree();

    // Set initial look-at position
    useEffect(() => {
      // Set the initial look-at position here
      // camera.position.set(0, 2, 5);
      camera.lookAt(new THREE.Vector3(0,0,0));
    }, [camera]);
    const rididBodyProps = {colliders:'cuboid', type:"fixed"}
    return (
      <>
      
<group position={position} scale={scale}>

          <group rotation={[Math.PI / 2, 0, 0]} position={[0,0,0]}>
            <RigidBody {...rididBodyProps}>
            <mesh geometry={targetNodes.Cylinder015.geometry}>
              <meshStandardMaterial
              
              args={[targetMaterials["White.024"]]}
              aoMapIntensity={0}
              envMapIntensity={0.7}
              color={[1, 0, 0]}
              ></meshStandardMaterial>
            </mesh>

            <mesh
              geometry={targetNodes.Cylinder015_1.geometry}
              material={targetMaterials["White.024"]}
              material-color={[1, 1, 8]}
              />
              </RigidBody>
          </group>

          <group rotation={[Math.PI / 2, 0, 0]} position={[targetsWidth, -targetsHeightDiff,0]} rotation-z={-targetSpin}>
            <RigidBody {...rididBodyProps}>

            <mesh geometry={targetNodes.Cylinder015.geometry}>
              <meshStandardMaterial
                args={[targetMaterials["White.024"]]}
                aoMapIntensity={0}
                envMapIntensity={0.7}
                color={[1, 0, 0]}
                ></meshStandardMaterial>
            </mesh>

            <mesh
              geometry={targetNodes.Cylinder015_1.geometry}
              material={targetMaterials["White.024"]}
              material-color={[1, 1, 8]}
              />
                </RigidBody>
          </group>

          <group rotation={[Math.PI / 2, 0, 0]} position={[-targetsWidth,-targetsHeightDiff,0]} rotation-z={targetSpin}>
            <RigidBody {...rididBodyProps}>

            <mesh geometry={targetNodes.Cylinder015.geometry}>
              <meshStandardMaterial
                args={[targetMaterials["White.024"]]}
                aoMapIntensity={0}
                envMapIntensity={0.7}
                color={[1, 0, 0]}
                ></meshStandardMaterial>
            </mesh>

            <mesh
              geometry={targetNodes.Cylinder015_1.geometry}
              material={targetMaterials["White.024"]}
              material-color={[1, 1, 8]}
              />
              </RigidBody>
          </group>
        
              </group>

              <group >
            </group>
        
              </>
  );
}

export default Target;

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/shooting-target/model.gltf"
);

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target/model.gltf"
);

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target/model.gltf"
);
