import { useRef, Suspense, useEffect, useState } from "react";
import "../App.css";

import { Canvas, useFrame, useThree,  } from "@react-three/fiber";
import {
  useGLTF,
  Stage,
  OrthographicCamera,
  OrbitControls, PerspectiveCamera
} from "@react-three/drei";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { Perf } from "r3f-perf";
import * as THREE from 'three'
import Cannon from "./Cannon";
function Target({colorRed,}) {
  const scale = [1.5,1.5,1.5]
  const { nodes: targetNodes, materials: targetMaterials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target/model.gltf"
  );
    // useFrame((state,delta) => {
        // state.camera.lookAt([0,0,0])
    const { camera, scene } = useThree();

    // Set initial look-at position
    useEffect(() => {
      // Set the initial look-at position here
      // camera.position.set(0, 2, 5);
      camera.lookAt(new THREE.Vector3(0,0,0));
    }, [camera]);
  return (
    <>
      
<group position={[0,1,0]} scale={scale}>

          <group rotation={[Math.PI / 2, 0, 0]} position={[0,2,0]}>
            <mesh geometry={targetNodes.Cylinder015.geometry}>
              <meshStandardMaterial
                args={[targetMaterials["White.024"]]}
                aoMapIntensity={0}
                envMapIntensity={0.7}
                color={[1, 0, 0]}
                ></meshStandardMaterial>
            </mesh>

            <mesh
              geometry={targetNodes.Cylinder015_1.geometry}
              material={targetMaterials["White.024"]}
              material-color={[1, 1, 8]}
              />
          </group>

          <group rotation={[Math.PI / 2, 0, 0]} position={[4,1,0]} rotation-z={Math.PI * -1.7}>
            <mesh geometry={targetNodes.Cylinder015.geometry}>
              <meshStandardMaterial
                args={[targetMaterials["White.024"]]}
                aoMapIntensity={0}
                envMapIntensity={0.7}
                color={[1, 0, 0]}
                ></meshStandardMaterial>
            </mesh>

            <mesh
              geometry={targetNodes.Cylinder015_1.geometry}
              material={targetMaterials["White.024"]}
              material-color={[1, 1, 8]}
              />
          </group>

          <group rotation={[Math.PI / 2, 0, 0]} position={[-4,1,0]} rotation-z={Math.PI * 1.7}>
            <mesh geometry={targetNodes.Cylinder015.geometry}>
              <meshStandardMaterial
                args={[targetMaterials["White.024"]]}
                aoMapIntensity={0}
                envMapIntensity={0.7}
                color={[1, 0, 0]}
                ></meshStandardMaterial>
            </mesh>

            <mesh
              geometry={targetNodes.Cylinder015_1.geometry}
              material={targetMaterials["White.024"]}
              material-color={[1, 1, 8]}
              />
          </group>
        
              </group>

              <group >
            </group>
        
              </>
  );
}

export default Target;

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/shooting-target/model.gltf"
);

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target/model.gltf"
);

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/target/model.gltf"
);
