/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, Float, 

 } from '@react-three/drei'
import * as THREE from 'three'

export default  function Diamond(props) {
    const { nodes, materials } = useGLTF('./model.gltf')
  const group = useRef()
  console.log(materials.Material);
  return (
    <Float 
    speed={10}
    rotationIntensity={1} // XYZ rotation intensity, defaults to 1
  floatIntensity={0.9} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
  floatingRange={[0, 0.75]}>

    <group ref={group} {...props} dispose={null}>
<mesh geometry={nodes.Diamond.geometry} position={[3, 0, 0,]}  scale={[2.5,2.5,2.5]}>
<meshStandardMaterial args={[materials.Material]} aoMapIntensity={0} envMapIntensity={0.7} color={[12,5,5]}></meshStandardMaterial>
</mesh>

    </group>
    </Float>
  )
}

useGLTF.preload('./model.gltf')